"""initial schema

Revision ID: 82ae1291398a
Revises: 
Create Date: 2026-03-05 00:03:46.831418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ae1291398a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influencer_profiles', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('influencer_profiles', sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=True))
    op.add_column('influencer_profiles', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('influencer_profiles', sa.Column('subscription_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer_profiles', 'subscription_status')
    op.drop_column('influencer_profiles', 'subscription_tier')
    op.drop_column('influencer_profiles', 'stripe_onboarding_complete')
    op.drop_column('influencer_profiles', 'stripe_account_id')
    # ### end Alembic commands ###
