"""add_proof_screenshot_fulfilled_at_dispute

Revision ID: cc4589f91ae9
Revises: 82ae1291398a
Create Date: 2026-03-08 20:15:03.448958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4589f91ae9'
down_revision: Union[str, Sequence[str], None] = '82ae1291398a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_requests', sa.Column('proof_screenshot_url', sa.String(), nullable=True))
    op.add_column('engagement_requests', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('engagement_requests', sa.Column('dispute_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_requests', 'dispute_reason')
    op.drop_column('engagement_requests', 'fulfilled_at')
    op.drop_column('engagement_requests', 'proof_screenshot_url')
    # ### end Alembic commands ###
